//! `mts_schema` -- the FlatBuffers-generated Rust bindings for `mts_schema.fbs` (owned by the
//! separate `schema` repo). As of 2026-10-09 (coherence audit §3.3) this one file also holds the
//! backtest-artifact tables (`BacktestFrame`, `RunManifest`, `TradeRecord`, ...) -- formerly a
//! separate `backtest_schema.fbs` that `include`d this one, merged because the include
//! relationship forced opposite per-language codegen workarounds (Python needed isolated staging
//! to avoid flatc re-stubbing included types; Rust needed `--rust-module-root-file` to make
//! cross-file references resolve at all). One file, one `flatc --rust` invocation, no workaround
//! needed for any language.
//!
//! Generated code lives under `src/generated/` and is regenerated by
//! `schema/regenerate_schema.sh` (the SAME script that already writes the C++ headers into
//! `MindfulTrader/include/generated/` and the Python bindings into `lbrnet/lbrnet/generated/` --
//! this is a third target on that one script, not a new mechanism). Never hand-edit anything
//! under `generated/`.
//!
//! The `#[allow(...)]` list below is wider than the generic "lint-suppressing wrapper" pattern
//! (infrastructure guide §5.1, copied from Atratus): this workspace additionally denies
//! `unsafe_op_in_unsafe_fn` and `clippy::unwrap_used` at `[workspace.lints]` (neither is part of
//! the `clippy::all` group Atratus relies on), and flatc's generated code trips both. Both must
//! stay in this list or `cargo build`/`cargo clippy` hard-fail the moment this crate is touched.
#[path = "generated/mts_schema_generated.rs"]
#[allow(
    unused_imports,
    dead_code,
    clippy::all,
    clippy::unwrap_used,
    unsafe_op_in_unsafe_fn,
    missing_debug_implementations
)]
pub mod generated;
