//! `mts_schema` -- the FlatBuffers-generated Rust bindings for `mts_schema.fbs` and
//! `backtest_schema.fbs` (owned by the separate `schema` repo).
//!
//! Generated code lives under `src/generated/` and is regenerated by
//! `schema/regenerate_schema.sh` (the SAME script that already writes the C++ headers into
//! `MindfulTrader/include/generated/` and the Python bindings into `lbrnet/lbrnet/generated/` --
//! this is a third target on that one script, not a new mechanism). Never hand-edit anything
//! under `generated/`.
//!
//! `--rust-module-root-file` is required (not plain `--rust`): `backtest_schema.fbs` includes
//! `mts_schema.fbs`, and its generated code references `crate::generated::mts::schema::*`. Without
//! `--rust-module-root-file`, flatc emits two self-contained single-file modules that can't see
//! each other (`E0433: cannot find \`schema\` in \`super\``); with it, both schemas generate into
//! one shared `mts::{schema,backtest,training}` module tree rooted at `generated/mod.rs`.
//!
//! The `#[allow(...)]` list below is wider than the generic "lint-suppressing wrapper" pattern
//! (infrastructure guide §5.1, copied from Atratus): this workspace additionally denies
//! `unsafe_op_in_unsafe_fn` and `clippy::unwrap_used` at `[workspace.lints]` (neither is part of
//! the `clippy::all` group Atratus relies on), and flatc's generated code trips both (119 and 446
//! occurrences respectively, verified 2026-10-09). Both must stay in this list or `cargo
//! build`/`cargo clippy` hard-fail the moment this crate is touched.
#[path = "generated/mod.rs"]
#[allow(
    unused_imports,
    dead_code,
    clippy::all,
    clippy::unwrap_used,
    unsafe_op_in_unsafe_fn,
    missing_debug_implementations
)]
pub mod generated;
