#!/usr/bin/env python3
"""Percentile-matches PositionManager.cpp's live fractal_dim gate thresholds
(1.6 / 1.3, PositionManager.cpp:2144-2146) against the new 400-bar window,
using a paired (fractal_dim@30, fractal_dim@400) sample generated by
tools/observation_vector/fractal_dim_threshold_migration.cpp (#includes the real, unmodified
include/SevcikFractalDimension.h against real MES TS2/60min data) -- same
methodology as Task 7's kurtosis/skewness threshold migration
(tools/observation_vector/analyze_kurtosis_threshold_migration.py).

Usage (mts env):
    source /home/rcruz/anaconda3/etc/profile.d/conda.sh && mamba activate mts
    cd /home/rcruz/devel/VSCode/MindfulTrader
    python3 tools/observation_vector/fractal_dim_threshold_migration.py
"""

import subprocess
import sys
from pathlib import Path

import numpy as np
import pandas as pd


WAVE_60M = Path("/home/rcruz/devel/VSCode/lbrnet/data/raw/mes_wave_60m.parquet")
TOOLS_DIR = Path(__file__).resolve().parent
DRIVER_SRC = TOOLS_DIR / "fractal_dim_threshold_migration.cpp"
DRIVER_BIN = TOOLS_DIR / "fractal_dim_threshold_migration"
INCLUDE_DIR = TOOLS_DIR.parent / "include"
SCRATCH_DIR = Path("/tmp/fractal_dim_threshold_migration_scratch")
CLOSES_CSV = SCRATCH_DIR / "closes.csv"
PAIRED_CSV = SCRATCH_DIR / "paired.csv"

# PositionManager.cpp:2144-2146's current live thresholds, calibrated against
# the old 30-bar window.
OLD_THRESHOLDS = {
    "fractal_dim_high (PositionManager.cpp:2144, lrc.fractalDim > 1.6)": 1.6,
    "fractal_dim_low (PositionManager.cpp:2146, lrc.fractalDim < 1.3)": 1.3,
}


def export_closes_csv() -> None:
    SCRATCH_DIR.mkdir(parents=True, exist_ok=True)
    df = pd.read_parquet(WAVE_60M).sort_values("timestamp_us").reset_index(drop=True)
    assert df["timestamp_us"].is_monotonic_increasing, "timestamps not sorted/unique"
    df[["timestamp_us", "close"]].to_csv(CLOSES_CSV, index=False)
    print(f"exported {len(df)} bars to {CLOSES_CSV}", file=sys.stderr)


def build_driver_if_needed() -> None:
    if DRIVER_BIN.exists() and DRIVER_BIN.stat().st_mtime > DRIVER_SRC.stat().st_mtime:
        return
    cmd = ["g++", "-O2", "-std=c++17", f"-I{INCLUDE_DIR}", str(DRIVER_SRC), "-o", str(DRIVER_BIN)]
    print(f"building driver: {' '.join(cmd)}", file=sys.stderr)
    subprocess.run(cmd, check=True)


def run_driver() -> None:
    cmd = [str(DRIVER_BIN), str(CLOSES_CSV), str(PAIRED_CSV)]
    print(f"running driver: {' '.join(cmd)}", file=sys.stderr)
    subprocess.run(cmd, check=True)


def main() -> None:
    if not CLOSES_CSV.exists():
        export_closes_csv()
    build_driver_if_needed()
    if not PAIRED_CSV.exists() or PAIRED_CSV.stat().st_mtime < DRIVER_BIN.stat().st_mtime:
        run_driver()

    df = pd.read_csv(PAIRED_CSV)
    old_arr = df["fractal_dim_30"].to_numpy()
    new_arr = df["fractal_dim_400"].to_numpy()

    print(f"Paired sample size: {len(df)}")
    print(
        f"fractal_dim@30:  mean={old_arr.mean():.4f} median={np.median(old_arr):.4f} "
        f"p10={np.percentile(old_arr, 10):.4f} p90={np.percentile(old_arr, 90):.4f}"
    )
    print(
        f"fractal_dim@400: mean={new_arr.mean():.4f} median={np.median(new_arr):.4f} "
        f"p10={np.percentile(new_arr, 10):.4f} p90={np.percentile(new_arr, 90):.4f}"
    )
    print()
    for name, old_threshold in OLD_THRESHOLDS.items():
        percentile = float((old_arr <= old_threshold).mean() * 100.0)
        mapped = float(np.percentile(new_arr, percentile))
        print(f"{name}: old={old_threshold} (P{percentile:.1f}) -> new={mapped:.4f}")

    corr = np.corrcoef(old_arr, new_arr)[0, 1]
    print(
        f"\ncorrelation(fractal_dim@30, fractal_dim@400) = {corr:.4f} "
        f"(sanity check -- expect positive but well below 1.0, different windows measuring "
        f"related but distinct path-roughness horizons)"
    )


if __name__ == "__main__":
    main()
